@base_url=http://localhost:5286
###
{{base_url}}/pair
###
{{base_url}}/pair/5
###
{{base_url}}/consonnes/hello
###
{{base_url}}/consonnes/aaabb
###
{{base_url}}/palindrome/elle
###
{{base_url}}/palindrome/tintin
###
{{base_url}}/ez/palindrome/elle
###
{{base_url}}/ez/palindrome/tintin
###
{{base_url}}/example/schtroumpf/
###
{{base_url}}/schtroumpf/5/2
###
{{base_url}}/notes
###
{{base_url}}/notes/7